### PR TITLE
Fix for receipt format from GetTxnBodiesForTxBlock(Ex)

### LINKED ISSUE #1883: Z2-Converter : GetTxnBodiesForTxBlock shows incorrect data
I have attached the complete api response of zq1 and zq2.
Observation:
Showing one ID difference
```
    ZQ2 -> {'ID': 'b219883c0c22ef50a590d26be5a6c5acefbe41d5f2cac105aa8dc7765d6a03ca', 'amount': '52568853093169', 'gasLimit': '50', 'gasPrice': '2000000000', 'nonce': '17313', 'receipt': {'block_hash': [66, 77, 167, 225, 89, 176, 164, 80, 76, 227, 7, 149, 43, 40, 91, 126, 182, 237, 38, 147, 223, 65, 204, 129, 168, 233, 104, 98, 245, 140, 75, 155], 'index': 7, 'tx_hash': [178, 25, 136, 60, 12, 34, 239, 80, 165, 144, 210, 107, 229, 166, 197, 172, 239, 190, 65, 213, 242, 202, 193, 5, 170, 141, 199, 118, 93, 106, 3, 202], 'success': True, 'gas_used': 50, 'cumulative_gas_used': 50, 'contract_address': None, 'logs': [], 'transitions': [], 'accepted': None, 'errors': {}, 'exceptions': []}, 'senderPubKey': '0x02fcc71e2ab9390b45e6660b0b99f4784b72e74678a7b8af0c3cc5092b6bd2f95d', 'signature': '0x4ea9d69ffab3986b85cd00800447ca475f4e10d154e3870be5ffcc28337bef733f23581495e7d34579f814b1b8e803f22fc393f199354df11ff5107a272ba7b6', 'toAddr': '0xC7FB1d50257f69282EA51b3576C51F88789A2F10', 'version': '65537'}
    ZQ1 -> {'ID': 'b219883c0c22ef50a590d26be5a6c5acefbe41d5f2cac105aa8dc7765d6a03ca', 'amount': '52568853093169', 'gasLimit': '50', 'gasPrice': '2000000000', 'nonce': '17314', 'receipt': {'cumulative_gas': '50', 'epoch_num': '3277414', 'success': True}, 'senderPubKey': '0x02FCC71E2AB9390B45E6660B0B99F4784B72E74678A7B8AF0C3CC5092B6BD2F95D', 'signature': '0x4EA9D69FFAB3986B85CD00800447CA475F4E10D154E3870BE5FFCC28337BEF733F23581495E7D34579F814B1B8E803F22FC393F199354DF11FF5107A272BA7B6', 'toAddr': 'c7fb1d50257f69282ea51b3576c51f88789a2f10', 'version': '65537'}
[txnBodies.txt](https://github.com/user-attachments/files/17900547/txnBodies.txt)

### PR DESCRIPTION
**Pull request by maxconway**
- closes #1883

### CODE REVIEW

File: zilliqa/src/api/zil.rs [hunk 1]
```diff
@@ -1036,6 +1037,11 @@ fn extract_transaction_bodies(block: &Block, node: &Node) -> Result<Vec<Transact
         let receipt = node
             .get_transaction_receipt(*hash)?
             .ok_or(anyhow!("Transaction receipt missing"))?;
+        let receipt_response = TransactionReceiptResponse {
+            cumulative_gas: ScillaGas(receipt.cumulative_gas_used.0).to_string(),
```
Comment (JamesHinshelwood) [inline zilliqa/src/api/zil.rs:1041]: Shouldn't this be `receipt.cumulative_gas_used.into()`, so the amount gets converted from `EvmGas` to `ScillaGas`?

Comment (maxconway) [reply zilliqa/src/api/zil.rs:1041]: I copied this from the code for GetTxResponse, so I'm guessing it's wrong there too, I'll fix that at the same time

Comment (maxconway) [reply zilliqa/src/api/zil.rs]: Pushed

**Review by JamesHinshelwood — APPROVED** [review]
