### PR TITLE
Fix local docker compose runs

### LINKED ISSUE #2114: Support multiple bootstrap nodes
The job of bootstrap nodes aka boot nodes is to facilitate peer discovery. It shall be possible to specify all bootstrap nodes with a singe DNS name instead of their IP addresses. However, bootstrap nodes like every other node in the p2p protocol need a unique peer id.

### PR DESCRIPTION
**Pull request by JamesHinshelwood**
This adds support for multiple bootstrap peers. We use this in the local docker compose set up to ensure all nodes have at least one other node to talk to at startup, which they can use to find their own external address via autonat.

This also means we can remove the incorrect code where we always trust our observed external address once a single peer reports one. Instead, the external address candidates are passed to autonat and confirmed later.

The configuration change is backwards compatible, because we support either a single entry or a list of bootstrap peers now.

Fixes #2114.

### CODE REVIEW

**Review by frankmeds — APPROVED** [review]

**Comment by shawn-zil** [comment]
@JamesHinshelwood i think one side-effect of this is that, while local docker is able to run (because each node is now connected to the 2 bootstraps) syncing is now only syncing against 2 nodes, not 4 - when I spin up a new node.

File: zilliqa/src/p2p_node.rs [hunk 1]
```diff
@@ -254,20 +254,6 @@ impl P2pNode {
                         SwarmEvent::NewListenAddr { address, .. } => {
                             info!(%address, "P2P swarm listening on");
                         }
-                        SwarmEvent::Behaviour(BehaviourEvent::Identify(identify::Event::Received { peer_id, info: identify::Info{ listen_addrs, observed_addr, protocols, .. }, .. })) => {
```
Comment (shawn-zil) [inline zilliqa/src/p2p_node.rs:257]: I believe that this is actually needed - https://docs.rs/libp2p-kad/latest/libp2p_kad/#important-discrepancies
> Peer Discovery with Identify In other libp2p implementations, the [Identify](https://github.com/libp2p/specs/tree/master/identify) protocol might be seen as a core protocol. Rust-libp2p tries to stay as generic as possible, and does not make this assumption. This means that the Identify protocol must be manually hooked up to Kademlia through calls to [Behaviour::add_address](https://docs.rs/libp2p-kad/latest/libp2p_kad/struct.Behaviour.html#method.add_address). If you choose not to use the Identify protocol, and do not provide an alternative peer discovery mechanism, a Kademlia node will not discover nodes beyond the network’s [boot nodes](https://docs.libp2p.io/concepts/glossary/#boot-node). Without the Identify protocol, existing nodes in the kademlia network cannot obtain the listen addresses of nodes querying them, and thus will not be able to add them to their routing table.

Comment (shawn-zil) [reply zilliqa/src/p2p_node.rs:257]: This might explain why I'm seeing only syncing against 2 nodes on docker, now.
